# Generated by Django 5.0.1 on 2024-02-03 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_number', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35)),
                ('course', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=10)),
                ('tuition_fee', models.IntegerField()),
                ('insurance_fee', models.IntegerField()),
                ('examination_fee', models.IntegerField()),
                ('registration_fee', models.IntegerField()),
                ('gymkhana_fee', models.IntegerField()),
                ('medical_fee', models.IntegerField()),
                ('student_benevolent_fund', models.IntegerField()),
                ('lab_fee', models.IntegerField()),
                ('semester_mess_advance', models.IntegerField()),
                ('one_time_fee', models.IntegerField()),
                ('refundable_security_deposit', models.IntegerField()),
                ('accomodation_charges', models.IntegerField()),
                ('student_welfare_fund', models.IntegerField()),
                ('mess_rebate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.students')),
            ],
        ),
        migrations.CreateModel(
            name='GatewayPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_portal.students')),
            ],
        ),
    ]
