# Generated by Django 5.0.4 on 2024-04-17 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='type',
        ),
    ]
