# Generated by Django 5.0.1 on 2024-03-27 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRemission',
            fields=[
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='admin_portal.students')),
                ('percentage', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='students',
            name='fee_arrear',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='students',
            name='fee_payable',
            field=models.IntegerField(default=0),
        ),
    ]
