# Generated by Django 5.0.4 on 2024-04-17 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_remove_payments_mode_remove_payments_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentcomponents',
            name='id',
        ),
        migrations.AlterField(
            model_name='paymentcomponents',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='components', serialize=False, to='admin_portal.payments'),
        ),
    ]
