# Generated by Django 5.0.1 on 2024-03-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0002_alter_customuser_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
