# Generated by Django 5.0.4 on 2024-04-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_alter_students_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='category',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='students',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='students',
            name='roll_number',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
