# Generated by Django 5.0.4 on 2024-04-17 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_remove_paymentcomponents_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentsemesterpayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='csempayment', to='admin_portal.payments'),
        ),
    ]
