# Generated by Django 5.0.1 on 2024-03-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_alter_customuser_isadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='loan_fee',
            field=models.IntegerField(default=0),
        ),
    ]
