# Generated by Django 5.0.1 on 2024-03-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0003_alter_customuser_isadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='accomodation_charges',
            new_name='accommodation_charges',
        ),
    ]
