# Generated by Django 5.0.1 on 2024-03-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_alter_feeremission_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GatewayPayments',
            new_name='Payments',
        ),
        migrations.DeleteModel(
            name='LoanPayments',
        ),
    ]
