# Generated by Django 5.0.1 on 2024-03-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_rename_accomodation_charges_students_accommodation_charges'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=15)),
                ('tuition_fee', models.IntegerField()),
                ('insurance_fee', models.IntegerField()),
                ('examination_fee', models.IntegerField()),
                ('registration_fee', models.IntegerField()),
                ('gymkhana_fee', models.IntegerField()),
                ('medical_fee', models.IntegerField()),
                ('student_benevolent_fund', models.IntegerField()),
                ('lab_fee', models.IntegerField()),
                ('semester_mess_advance', models.IntegerField()),
                ('one_time_fee', models.IntegerField()),
                ('refundable_security_deposit', models.IntegerField()),
                ('accommodation_charges', models.IntegerField()),
                ('student_welfare_fund', models.IntegerField()),
            ],
        ),
    ]
