# Generated by Django 5.0.4 on 2024-04-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0004_alter_currentsemesterpayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentcomponents',
            name='amt',
            field=models.IntegerField(default=0),
        ),
    ]
