# Generated by Django 5.0.1 on 2024-04-01 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0006_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='tuition_fee',
            new_name='base_tuition_fee',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='tuition_fee',
            new_name='base_tution_fee',
        ),
    ]
