# Generated by Django 5.0.1 on 2024-04-01 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0007_rename_tuition_fee_feestructure_base_tuition_fee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='base_tution_fee',
            new_name='base_tuition_fee',
        ),
    ]
