# Generated by Django 5.0.1 on 2024-04-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0009_payments_fee_payable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='fee_payable',
            field=models.IntegerField(),
        ),
    ]
