# Generated by Django 4.2.6 on 2024-04-04 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0010_alter_payments_fee_payable'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentStats',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='admin_portal.students')),
                ('hasReceipt', models.BooleanField(default=False)),
            ],
        ),
    ]
