# Generated by Django 5.0.1 on 2024-04-07 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0011_studentstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='fee_payable',
            new_name='fee_paid',
        ),
    ]
