# Generated by Django 4.2.6 on 2024-04-13 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0012_rename_fee_payable_students_fee_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentStats',
        ),
    ]
