# Generated by Django 5.0.4 on 2024-04-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0013_delete_studentstats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeremission',
            name='percentage',
            field=models.CharField(choices=[('1', '1'), ('2/3', '2/3')], max_length=3),
        ),
    ]
