# Generated by Django 5.0.4 on 2024-04-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_portal', '0014_alter_feeremission_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='fee_payable',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='students',
            name='tuition_fee',
            field=models.IntegerField(default=0),
        ),
    ]
